### ISSUE TITLE
無駄エラー

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-backend#43]
ログに無駄なエラーと対処した方が良さそうなエラーがあった。
```python
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/home/arch/.local/lib/python3.9/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "/home/arch/rt/cogs/captcha/__init__.py", line 171, in on_member_join
    captcha = self.captchas[row[2]]
IndexError: list index out of range
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/home/arch/.local/lib/python3.9/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "/home/arch/rt/cogs/captcha/__init__.py", line 171, in on_member_join
    captcha = self.captchas[row[2]]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 994, in invoke
    await ctx.command.invoke(ctx)
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 886, in invoke
    await self.prepare(ctx)
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 820, in prepare
    await self._parse_arguments(ctx)
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 726, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 578, in transform
    return await run_converters(ctx, converter, argument, param)  # type: ignore
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/converter.py", line 1149, in run_converters
    raise BadUnionArgument(param, union_args, errors)
discord.ext.commands.errors.BadUnionArgument: Could not convert "channel" into VoiceChannel or StageChannel.
```

**Comment by tasuren** [comment]
このエラーがでないようにした。
