### ISSUE TITLE
6chエラー

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-backend#60]
```python
コマンドの実行中にエラーが発生しました。
Traceback (most recent call last):
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 167, in wrapped
    ret = await coro(args, **kwargs)
  File "/home/arch/rt/cogs/6ch.py", line 91, in new
    await self.save(self.path, self.data, 4)
  File "/home/arch/rt/cogs/6ch.py", line 33, in save
    await f.write(dumps(data), indent=indent)
  File "/usr/lib/python3.9/site-packages/aiofiles/threadpool/utils.py", line 36, in method
    return (yield from self._loop.run_in_executor(self._executor, cb))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(self.args, self.kwargs)
TypeError: TextIOWrapper.write() takes no keyword arguments

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 994, in invoke
    await ctx.command.invoke(ctx)
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1448, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 894, in invoke
    await injected(*ctx.args, ctx.kwargs)
  File "/home/arch/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 176, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: TextIOWrapper.write() takes no keyword arguments 
```
原因はindentというキーワード引数の位置が間違ってるから。

**Comment by tasuren** [comment]
バグを修正しました。
